(define (problem robotics1) (:domain robotics)
(:objects
random_object random_object0 random_object1 random_object2 random_object3 random_object4 random_object5 random_object6 random_object7 random_object8 random_object9 random_object10 random_object11 random_object12 random_object13 random_object14 random_object15 random_object16 random_object17 random_object18 random_object19 random_object20 random_object21 random_object22 random_object23 random_object24 random_object25 random_object26 random_object27 random_object28 random_object29 random_object30 random_object31 random_object32 random_object33 random_object34

loc_random_object loc_random_object0 loc_random_object1 loc_random_object2 loc_random_object3 loc_random_object4 loc_random_object5 loc_random_object6 loc_random_object7 loc_random_object8 loc_random_object9 loc_random_object10 loc_random_object11 loc_random_object12 loc_random_object13 loc_random_object14 loc_random_object15 loc_random_object16 loc_random_object17 loc_random_object18 loc_random_object19 loc_random_object20 loc_random_object21 loc_random_object22 loc_random_object23 loc_random_object24 loc_random_object25 loc_random_object26 loc_random_object27 loc_random_object28 loc_random_object29 loc_random_object30 loc_random_object31 loc_random_object32 loc_random_object33 loc_random_object34
gp_random_object gp_random_object0 gp_random_object1 gp_random_object2 gp_random_object3 gp_random_object4 gp_random_object5 gp_random_object6 gp_random_object7 gp_random_object8 gp_random_object9 gp_random_object10 gp_random_object11 gp_random_object12 gp_random_object13 gp_random_object14 gp_random_object15 gp_random_object16 gp_random_object17 gp_random_object18 gp_random_object19 gp_random_object20 gp_random_object21 gp_random_object22 gp_random_object23 gp_random_object24 gp_random_object25 gp_random_object26 gp_random_object27 gp_random_object28 gp_random_object29 gp_random_object30 gp_random_object31 gp_random_object32 gp_random_object33 gp_random_object34

Table6
blf_Table6

robotInitLoc
)


(:init 
(at random_object loc_random_object)
(at random_object0 loc_random_object0)
(at random_object1 loc_random_object1)
(at random_object10 loc_random_object10)
(at random_object11 loc_random_object11)
(at random_object12 loc_random_object12)
(at random_object13 loc_random_object13)
(at random_object14 loc_random_object14)
(at random_object15 loc_random_object15)
(at random_object16 loc_random_object16)
(at random_object17 loc_random_object17)
(at random_object18 loc_random_object18)
(at random_object19 loc_random_object19)
(at random_object2 loc_random_object2)
(at random_object20 loc_random_object20)
(at random_object21 loc_random_object21)
(at random_object22 loc_random_object22)
(at random_object23 loc_random_object23)
(at random_object24 loc_random_object24)
(at random_object25 loc_random_object25)
(at random_object26 loc_random_object26)
(at random_object27 loc_random_object27)
(at random_object28 loc_random_object28)
(at random_object29 loc_random_object29)
(at random_object3 loc_random_object3)
(at random_object30 loc_random_object30)
(at random_object31 loc_random_object31)
(at random_object32 loc_random_object32)
(at random_object33 loc_random_object33)
(at random_object34 loc_random_object34)
(at random_object4 loc_random_object4)
(at random_object5 loc_random_object5)
(at random_object6 loc_random_object6)
(at random_object7 loc_random_object7)
(at random_object8 loc_random_object8)
(at random_object9 loc_random_object9)
(isaccesspointfor blf_table6 table6)
(isgp gp_random_object random_object)
(isgp gp_random_object0 random_object0)
(isgp gp_random_object1 random_object1)
(isgp gp_random_object10 random_object10)
(isgp gp_random_object11 random_object11)
(isgp gp_random_object12 random_object12)
(isgp gp_random_object13 random_object13)
(isgp gp_random_object14 random_object14)
(isgp gp_random_object15 random_object15)
(isgp gp_random_object16 random_object16)
(isgp gp_random_object17 random_object17)
(isgp gp_random_object18 random_object18)
(isgp gp_random_object19 random_object19)
(isgp gp_random_object2 random_object2)
(isgp gp_random_object20 random_object20)
(isgp gp_random_object21 random_object21)
(isgp gp_random_object22 random_object22)
(isgp gp_random_object23 random_object23)
(isgp gp_random_object24 random_object24)
(isgp gp_random_object25 random_object25)
(isgp gp_random_object26 random_object26)
(isgp gp_random_object27 random_object27)
(isgp gp_random_object28 random_object28)
(isgp gp_random_object29 random_object29)
(isgp gp_random_object3 random_object3)
(isgp gp_random_object30 random_object30)
(isgp gp_random_object31 random_object31)
(isgp gp_random_object32 random_object32)
(isgp gp_random_object33 random_object33)
(isgp gp_random_object34 random_object34)
(isgp gp_random_object4 random_object4)
(isgp gp_random_object5 random_object5)
(isgp gp_random_object6 random_object6)
(isgp gp_random_object7 random_object7)
(isgp gp_random_object8 random_object8)
(isgp gp_random_object9 random_object9)
(location blf_table6)
(location gp_random_object)
(location gp_random_object0)
(location gp_random_object1)
(location gp_random_object10)
(location gp_random_object11)
(location gp_random_object12)
(location gp_random_object13)
(location gp_random_object14)
(location gp_random_object15)
(location gp_random_object16)
(location gp_random_object17)
(location gp_random_object18)
(location gp_random_object19)
(location gp_random_object2)
(location gp_random_object20)
(location gp_random_object21)
(location gp_random_object22)
(location gp_random_object23)
(location gp_random_object24)
(location gp_random_object25)
(location gp_random_object26)
(location gp_random_object27)
(location gp_random_object28)
(location gp_random_object29)
(location gp_random_object3)
(location gp_random_object30)
(location gp_random_object31)
(location gp_random_object32)
(location gp_random_object33)
(location gp_random_object34)
(location gp_random_object4)
(location gp_random_object5)
(location gp_random_object6)
(location gp_random_object7)
(location gp_random_object8)
(location gp_random_object9)
(location loc_random_object)
(location loc_random_object0)
(location loc_random_object1)
(location loc_random_object10)
(location loc_random_object11)
(location loc_random_object12)
(location loc_random_object13)
(location loc_random_object14)
(location loc_random_object15)
(location loc_random_object16)
(location loc_random_object17)
(location loc_random_object18)
(location loc_random_object19)
(location loc_random_object2)
(location loc_random_object20)
(location loc_random_object21)
(location loc_random_object22)
(location loc_random_object23)
(location loc_random_object24)
(location loc_random_object25)
(location loc_random_object26)
(location loc_random_object27)
(location loc_random_object28)
(location loc_random_object29)
(location loc_random_object3)
(location loc_random_object30)
(location loc_random_object31)
(location loc_random_object32)
(location loc_random_object33)
(location loc_random_object34)
(location loc_random_object4)
(location loc_random_object5)
(location loc_random_object6)
(location loc_random_object7)
(location loc_random_object8)
(location loc_random_object9)
(location robotinitloc)
(location table6)
(object random_object)
(object random_object0)
(object random_object1)
(object random_object10)
(object random_object11)
(object random_object12)
(object random_object13)
(object random_object14)
(object random_object15)
(object random_object16)
(object random_object17)
(object random_object18)
(object random_object19)
(object random_object2)
(object random_object20)
(object random_object21)
(object random_object22)
(object random_object23)
(object random_object24)
(object random_object25)
(object random_object26)
(object random_object27)
(object random_object28)
(object random_object29)
(object random_object3)
(object random_object30)
(object random_object31)
(object random_object32)
(object random_object33)
(object random_object34)
(object random_object4)
(object random_object5)
(object random_object6)
(object random_object7)
(object random_object8)
(object random_object9)
(Obstructs gp_random_object1 random_object random_object1)
(Obstructs gp_random_object1 random_object2 random_object1)
(Obstructs gp_random_object1 random_object3 random_object1)
(Obstructs gp_random_object2 random_object9 random_object2)
(Obstructs gp_random_object2 random_object random_object2)
(Obstructs gp_random_object3 random_object9 random_object3)
(Obstructs gp_random_object4 random_object5 random_object4)
(Obstructs gp_random_object7 random_object6 random_object7)
(Obstructs gp_random_object10 random_object14 random_object10)
(Obstructs gp_random_object10 random_object17 random_object10)
(Obstructs gp_random_object21 random_object20 random_object21)
(Obstructs gp_random_object21 random_object25 random_object21)
(Obstructs gp_random_object25 random_object18 random_object25)
(Obstructs gp_random_object26 random_object23 random_object26)
(Obstructs gp_random_object27 random_object33 random_object27)
(Obstructs gp_random_object34 random_object30 random_object34)
(robotat gp_random_object34))

(:goal (and (At random_object27 Table6)))
)