(define (problem robotics1) (:domain robotics)
(:objects
random_object random_object0 random_object1 random_object2 random_object3 random_object4 random_object5 random_object6 random_object7 random_object8 random_object9 random_object10 random_object11 random_object12 random_object13 random_object14 random_object15 random_object16 random_object17 random_object18 random_object19 random_object20 random_object21 random_object22 random_object23 random_object24 random_object25 random_object26 random_object27 random_object28 random_object29 random_object30 random_object31 random_object32 random_object33 random_object34 random_object35 random_object36 random_object37 random_object38 random_object39 random_object40 random_object41 random_object42 random_object43 random_object44 random_object45 random_object46 random_object47 random_object48 - object

loc_random_object loc_random_object0 loc_random_object1 loc_random_object2 loc_random_object3 loc_random_object4 loc_random_object5 loc_random_object6 loc_random_object7 loc_random_object8 loc_random_object9 loc_random_object10 loc_random_object11 loc_random_object12 loc_random_object13 loc_random_object14 loc_random_object15 loc_random_object16 loc_random_object17 loc_random_object18 loc_random_object19 loc_random_object20 loc_random_object21 loc_random_object22 loc_random_object23 loc_random_object24 loc_random_object25 loc_random_object26 loc_random_object27 loc_random_object28 loc_random_object29 loc_random_object30 loc_random_object31 loc_random_object32 loc_random_object33 loc_random_object34 loc_random_object35 loc_random_object36 loc_random_object37 loc_random_object38 loc_random_object39 loc_random_object40 loc_random_object41 loc_random_object42 loc_random_object43 loc_random_object44 loc_random_object45 loc_random_object46 loc_random_object47 loc_random_object48
gp_random_object gp_random_object0 gp_random_object1 gp_random_object2 gp_random_object3 gp_random_object4 gp_random_object5 gp_random_object6 gp_random_object7 gp_random_object8 gp_random_object9 gp_random_object10 gp_random_object11 gp_random_object12 gp_random_object13 gp_random_object14 gp_random_object15 gp_random_object16 gp_random_object17 gp_random_object18 gp_random_object19 gp_random_object20 gp_random_object21 gp_random_object22 gp_random_object23 gp_random_object24 gp_random_object25 gp_random_object26 gp_random_object27 gp_random_object28 gp_random_object29 gp_random_object30 gp_random_object31 gp_random_object32 gp_random_object33 gp_random_object34 gp_random_object35 gp_random_object36 gp_random_object37 gp_random_object38 gp_random_object39 gp_random_object40 gp_random_object41 gp_random_object42 gp_random_object43 gp_random_object44 gp_random_object45 gp_random_object46 gp_random_object47 gp_random_object48 - location



table6 blf_table6 robotInitLoc - location
)
(:init
(empty gripper)
(At random_object loc_random_object)
(At random_object0 loc_random_object0)
(At random_object1 loc_random_object1)
(At random_object2 loc_random_object2)
(At random_object3 loc_random_object3)
(At random_object4 loc_random_object4)
(At random_object5 loc_random_object5)
(At random_object6 loc_random_object6)
(At random_object7 loc_random_object7)
(At random_object8 loc_random_object8)
(At random_object9 loc_random_object9)
(At random_object10 loc_random_object10)
(At random_object11 loc_random_object11)
(At random_object12 loc_random_object12)
(At random_object13 loc_random_object13)
(At random_object14 loc_random_object14)
(At random_object15 loc_random_object15)
(At random_object16 loc_random_object16)
(At random_object17 loc_random_object17)
(At random_object18 loc_random_object18)
(At random_object19 loc_random_object19)
(At random_object20 loc_random_object20)
(At random_object21 loc_random_object21)
(At random_object22 loc_random_object22)
(At random_object23 loc_random_object23)
(At random_object24 loc_random_object24)
(At random_object25 loc_random_object25)
(At random_object26 loc_random_object26)
(At random_object27 loc_random_object27)
(At random_object28 loc_random_object28)
(At random_object29 loc_random_object29)
(At random_object30 loc_random_object30)
(At random_object31 loc_random_object31)
(At random_object32 loc_random_object32)
(At random_object33 loc_random_object33)
(At random_object34 loc_random_object34)
(At random_object35 loc_random_object35)
(At random_object36 loc_random_object36)
(At random_object37 loc_random_object37)
(At random_object38 loc_random_object38)
(At random_object39 loc_random_object39)
(At random_object40 loc_random_object40)
(At random_object41 loc_random_object41)
(At random_object42 loc_random_object42)
(At random_object43 loc_random_object43)
(At random_object44 loc_random_object44)
(At random_object45 loc_random_object45)
(At random_object46 loc_random_object46)
(At random_object47 loc_random_object47)
(At random_object48 loc_random_object48)
(RobotAt robotInitLoc)

(IsAccessPointFor blf_table6 table6)

(IsGP gp_random_object random_object)
(IsGP gp_random_object0 random_object0)
(IsGP gp_random_object1 random_object1)
(IsGP gp_random_object2 random_object2)
(IsGP gp_random_object3 random_object3)
(IsGP gp_random_object4 random_object4)
(IsGP gp_random_object5 random_object5)
(IsGP gp_random_object6 random_object6)
(IsGP gp_random_object7 random_object7)
(IsGP gp_random_object8 random_object8)
(IsGP gp_random_object9 random_object9)
(IsGP gp_random_object10 random_object10)
(IsGP gp_random_object11 random_object11)
(IsGP gp_random_object12 random_object12)
(IsGP gp_random_object13 random_object13)
(IsGP gp_random_object14 random_object14)
(IsGP gp_random_object15 random_object15)
(IsGP gp_random_object16 random_object16)
(IsGP gp_random_object17 random_object17)
(IsGP gp_random_object18 random_object18)
(IsGP gp_random_object19 random_object19)
(IsGP gp_random_object20 random_object20)
(IsGP gp_random_object21 random_object21)
(IsGP gp_random_object22 random_object22)
(IsGP gp_random_object23 random_object23)
(IsGP gp_random_object24 random_object24)
(IsGP gp_random_object25 random_object25)
(IsGP gp_random_object26 random_object26)
(IsGP gp_random_object27 random_object27)
(IsGP gp_random_object28 random_object28)
(IsGP gp_random_object29 random_object29)
(IsGP gp_random_object30 random_object30)
(IsGP gp_random_object31 random_object31)
(IsGP gp_random_object32 random_object32)
(IsGP gp_random_object33 random_object33)
(IsGP gp_random_object34 random_object34)
(IsGP gp_random_object35 random_object35)
(IsGP gp_random_object36 random_object36)
(IsGP gp_random_object37 random_object37)
(IsGP gp_random_object38 random_object38)
(IsGP gp_random_object39 random_object39)
(IsGP gp_random_object40 random_object40)
(IsGP gp_random_object41 random_object41)
(IsGP gp_random_object42 random_object42)
(IsGP gp_random_object43 random_object43)
(IsGP gp_random_object44 random_object44)
(IsGP gp_random_object45 random_object45)
(IsGP gp_random_object46 random_object46)
(IsGP gp_random_object47 random_object47)
(IsGP gp_random_object48 random_object48)

)


(:goal (and (at random_object8 table6)))

)